In [1]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import MultinomialNB

In [2]:
data=pd.read_csv('spamBase.data').as_matrix();

In [3]:
data

array([[  2.10000000e-01,   2.80000000e-01,   5.00000000e-01, ...,
          1.01000000e+02,   1.02800000e+03,   1.00000000e+00],
       [  6.00000000e-02,   0.00000000e+00,   7.10000000e-01, ...,
          4.85000000e+02,   2.25900000e+03,   1.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          4.00000000e+01,   1.91000000e+02,   1.00000000e+00],
       ..., 
       [  3.00000000e-01,   0.00000000e+00,   3.00000000e-01, ...,
          6.00000000e+00,   1.18000000e+02,   0.00000000e+00],
       [  9.60000000e-01,   0.00000000e+00,   0.00000000e+00, ...,
          5.00000000e+00,   7.80000000e+01,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   6.50000000e-01, ...,
          5.00000000e+00,   4.00000000e+01,   0.00000000e+00]])

In [4]:
len(data)

4600

In [7]:
np.random.shuffle(data)

In [8]:
data

array([[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          9.00000000e+00,   6.70000000e+01,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          1.60000000e+01,   4.00000000e+01,   1.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          2.00000000e+00,   7.00000000e+00,   0.00000000e+00],
       ..., 
       [  0.00000000e+00,   0.00000000e+00,   2.90000000e-01, ...,
          1.39000000e+02,   2.74000000e+02,   1.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          3.80000000e+01,   1.24000000e+02,   0.00000000e+00],
       [  8.00000000e-02,   0.00000000e+00,   8.00000000e-02, ...,
          4.00000000e+01,   6.73000000e+02,   0.00000000e+00]])

In [9]:
np.random.shuffle(data)

In [10]:
data

array([[  0.00000000e+00,   0.00000000e+00,   3.60000000e-01, ...,
          2.10000000e+01,   6.41000000e+02,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          3.40000000e+01,   1.82000000e+02,   0.00000000e+00],
       [  0.00000000e+00,   6.00000000e-02,   2.00000000e-01, ...,
          1.04000000e+02,   7.03000000e+02,   1.00000000e+00],
       ..., 
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          5.00000000e+00,   3.50000000e+01,   0.00000000e+00],
       [  0.00000000e+00,   3.40000000e-01,   0.00000000e+00, ...,
          1.50000000e+01,   9.60000000e+01,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          1.20000000e+01,   6.40000000e+01,   1.00000000e+00]])

In [13]:
X=data[:,:48]

In [14]:
X

array([[ 0.  ,  0.  ,  0.36, ...,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , ...,  0.  ,  0.  ,  0.84],
       [ 0.  ,  0.06,  0.2 , ...,  0.  ,  0.  ,  0.  ],
       ..., 
       [ 0.  ,  0.  ,  0.  , ...,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.34,  0.  , ...,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , ...,  0.  ,  0.  ,  0.  ]])

In [15]:
Y=data[:,-1]

In [16]:
Y

array([ 0.,  0.,  1., ...,  0.,  0.,  1.])

In [18]:
Xtrain=X[:-100,]
Ytrain=Y[:-100,]
Xtest=X[-100:,]
Ytest=Y[-100:,]

In [19]:
model=MultinomialNB()

In [20]:
model

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [22]:
model.fit(Xtrain,Ytrain)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [23]:
print "Classification rate for NB : " , model.score(Xtest,Ytest)

Classification rate for NB :  0.86
